version: '3.8'

services:
  birthcenter.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=birthcenter;Username=postgres;Password=postgres
    ports:
      - "7000:80"
    networks:
      - birthcenter_network

  postgres:
    ports:
      - "5432:5432"
    networks:
      - birthcenter_network